### ISSUE TITLE
Status Chooser - Options

### ISSUE THREAD

**Issue by gwaygenomics** [cognoma/frontend#1]
There was a lot of discussion last night about different screens a user will interact with (See cognoma/django-cognoma#13). One component of the screens we call `Status Chooser`. We can think of this option really as `Mutation Status Chooser` for the biologists, or the `Y` matrix for the machine learning enthusiasts. See cognoma/django-cognoma#3 for some additional comments. 

Essentially, the user will select a subset of genes that the backend will need to take in and process into a vector of 1's and 0's corresponding to the mutation status of samples (1 = mutation, 0 = [wild-type](https://en.wikipedia.org/wiki/Wild_type)). 

For the front end people, we need to view the `Status Chooser` as three possible types of user interactions:
1. **Text** - User will type gene identifiers directly into the screen
2. **Import Text** - User will upload a text file directly into the browser
3. **Neo4J Query** - this is where we will need to be creative!
   1. Compound
   2. Drug
   3. Biological Pathway
   4. Side Effect
   5. ...

For example, the Neo4J query interaction would be something like a dropdown menu with the compound, drug, pathway, etc. options listed above followed by a text box with auto-complete text options. This option will need to translate a user query into [the Cypher Language](https://neo4j.com/developer/cypher-query-language/,) to communicate with @dhimmel's network [hetionet](https://neo4j.het.io/browser/) to ultimately retrieve a list of genes that are associated with the user query (e.g. all genes associated with a specific drug)

**Comment by awm33** [comment]
@gwaygenomics For the gene list, I think I remember you mentioning some genes were ambiguous using the more generic notation and that we need to assist the user resolve the genes to a coding system?

**Comment by gwaygenomics** [comment]
@awm33 Great point. Yes, there are some ambiguous genes. It may also be nice to have an auto-complete option for the **Text** option listed above. 

Generally, I've found that cancer biologists (and biologists in general) prefer [HUGO symbols](http://www.genenames.org/about/faq/#whatisthehgnc "about HUGO") but computational biologists prefer [Entrez symbols](http://nar.oxfordjournals.org/content/39/suppl_1/D52 "about entrez") (this is pronounced like an Entree you would order at a restaurant). Biologists like the HUGO names because they can immediately identify what they are. Computational biologists like Entrez because they are more stable than HUGO being that they are unique and can map to different HUGO versions of the same gene.

For the **Import Text** option above - we should offer the user a dropdown selection of possible identifiers (e.g. `hugo_symbol`, `entrez_id`, `ensemble_id`, etc.) that the backend will need to translate into whatever the cancer-data people decide to use (see cognoma/cancer-data#6)

**Comment by awm33** [comment]
There's discussion of the core data model https://github.com/cognoma/django-cognoma/issues/2 The gene table should probably have a column for each codeing system, eg hugo_symbol, entrez_id, ensemble_id. You may also want to pick a standard for the app.

**Comment by cgreene** [comment]
In other applications (handled via django-genes) we have a xrid model that attaches these cross references to a cross reference database (xrdb). This can be dumped into a document that can be searched with elastic search. It tends to give pretty good results for getting biologists from any number of potential gene identifiers that they may have to the things they actually want.
