### ISSUE TITLE
Potential libraries to use for gene and sample selection

### ISSUE THREAD

**Issue by laszlokv** [cognoma/frontend#10]
@BobMiller, you mentioned I should post this as a separate issue.  I had this list of potential libraries to use for gene and sample selection (since each list will be huge):
o   https://jqueryui.com/autocomplete/#default
o   https://harvesthq.github.io/chosen/
o   https://select2.github.io/examples.html 
o   https://selectize.github.io/selectize.js/

**Comment by awm33** [comment]
Here's an angular "tag" style one

http://mbenford.github.io/ngTagsInput/

**Comment by keenleo** [comment]
I like the angular directive awm33 proposed. It looks good, we are already using angular and this will not introduce any new dependencies.
