### ISSUE TITLE
Add Cognoma logo somewhere on the website

### ISSUE THREAD

**Issue by dhimmel** [cognoma/frontend#100]
We have a nice cognoma logo ([SVG here](https://github.com/cognoma/cognoma/blob/master/media/logo/cognoma-bw.svg)). It would be great for branding if we could incorporate this logo somewhere in the frontend / cognoma.org.

**Comment by rdvelazquez** [comment]
The logo is already in the browser tab, which looks good. 

As far as adding the logo to the website itself, we could add a small white logo to the top left (see below). Let me know what you think.

Chrome:

![chrome](https://user-images.githubusercontent.com/25244432/31312350-8dd3fb98-ab8e-11e7-90d7-863a9d1aa8c8.png)

ie: 

![ie](https://user-images.githubusercontent.com/25244432/31312359-d39af5dc-ab8e-11e7-8819-ebf795a3c6a9.png)

**Comment by dhimmel** [comment]
Top right looks good to me.

Another option would be a light background watermark version in the large light frame.

**Comment by rdvelazquez** [comment]
I went with top left as opposed to top right because the submit button is in the top right.

I like the watermark background option best. I probably won't have time to do that before tomorrow night but if no one gets to that, I'll try and work on it later this week.

**Comment by dhimmel** [comment]
> I went with top left 

Yeah my bad. Top left makes more sense than top right.

> I probably won't have time to do that before tomorrow night but if no one gets to that, I'll try and work on it later this week.

No rush!
