### ISSUE TITLE
Compile Error 'angular-growl-v2'

### ISSUE THREAD

**Issue by rdvelazquez** [cognoma/frontend#103]
I'm having some trouble getting the fronted up and running on my computer. I am getting the following error: `gulp-notify: [Compile Error] Cannot find module 'angular-growl-v2' from '/home/Ryan/code/frontend/app/js'`. 
I've reproduced this error on Windows 10 using PowerShell and on the Windows Subsystem for Linux (WSL) using Ubuntu Bash. 

I was getting another error previously `npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2` but addressed this by using `npm install --no-optional` as recommended in this [issue](https://github.com/angular/angular/issues/13935#issuecomment-319077846). 

The localhost:3000 opens a blank browser window; small popup window at top right of browser that says "powered by browsersync"; and the cognoma log is shown in the browser tab.

The localhost:3001 opens a browsersync window.

Here's the complete PowerShell output:

> PS C:\Users\Ryan\documents\code\cognoma\frontend> npm install --no-optional
> PS C:\Users\Ryan\documents\code\cognoma\frontend> npm run dev
> 
> > Cognoma@0.0.0 dev C:\Users\Ryan\documents\code\cognoma\frontend
> > cross-env NODE_ENV=development ./node_modules/.bin/gulp dev
> 
> [13:49:38] Requiring external module babel-register
> [13:49:41] Using gulpfile ~\documents\code\cognoma\frontend\gulpfile.babel.js
> [13:49:41] Starting 'clean'...
> [13:49:41] Finished 'clean' after 19 ms
> [13:49:41] Starting 'dev'...
> [13:49:41] Starting 'styles'...
> [13:49:41] Starting 'images'...
> [13:49:41] Starting 'fonts'...
> [13:49:41] Starting 'views'...
> [13:49:41] Finished 'views' after 1.81 ms
> [13:49:42] Finished 'images' after 78 ms
> [13:49:42] Finished 'fonts' after 107 ms
> [13:49:42] Finished 'styles' after 801 ms
> [13:49:42] Starting 'browserify'...
> [13:49:42] Rebundling...
> [13:49:50] gulp-notify: [Compile Error] Cannot find module 'angular-growl-v2' from 'C:\Users\Ryan\documents\code\cognoma
> \frontend\app\js'
> [13:49:50] Finished rebundling in 7.54 s
> [13:49:50] Finished 'browserify' after 7.56 s
> [13:49:50] Starting 'browserSync'...
> [13:49:50] Finished 'browserSync' after 44 ms
> [13:49:50] Starting 'watch'...
> [13:49:50] Finished 'watch' after 121 ms
> [13:49:50] Finished 'dev' after 8.54 s
> [13:49:50] Finished rebundling in 7.76 s
> [Browsersync] Access URLs:
>  ----------------------------------
>        Local: http://localhost:3000
>     External: http://10.0.75.1:3000
>  ----------------------------------
>           UI: http://localhost:3001
>     UI External: http://10.0.75.1:3001
>  ----------------------------------
> [Browsersync] Serving files from: ./build/
> 
> 
> 

This is likely user error but I'm not finding much information online. Any advice on how to proceed? Thanks in advance!

**Comment by dcgoss** [comment]
Check this out and let me know if it helps: https://github.com/cognoma/frontend/pull/94

**Comment by rdvelazquez** [comment]
Thanks @dcgoss! That was very helpful.

I deleted the build and node_modules folders from my previous build attempts and then manually installed `angular-growl-v2` with `npm install angular-growl-v2` and re-built. It worked fine.
