### ISSUE TITLE
Limit gene selection to protein-coding genes only

### ISSUE THREAD

**Issue by dhimmel** [cognoma/frontend#106]
Currently our API queries to mygene.info are specified in

https://github.com/cognoma/frontend/blob/a1b22117460e57996d751c0bf899aaca0892c8f6/app/js/constants.js#L21-L29

I think we should also restrict to "protein-coding" genes, as users will be primarily interested in mutations for protein-coding genes. In general we will only have mutations for protein-coding genes, since we [require](https://github.com/cognoma/cancer-data/blob/1d961fb2201209b3ec4774aaadd36f36cf6d165e/2.TCGA-process.ipynb) mutations to be "gene-affecting".

It is possible to modify our query as per https://github.com/biothings/mygene.info/issues/24. We basically have to add ` AND type_of_gene:protein-coding`. I'm not sure exactly how to do this in `constants.js`. Note we can also do `q=type_of_gene:protein-coding AND XXX` where XXX is the user search term (order doesn't matter).

@rdvelazquez are you interested seeing if this change works? Currently, I think there is an error when the frontend specified genes that aren't in our mutation catalog, so this would minimize those occurrences.

**Comment by ramenhog** [comment]
@dhimmel I'm not sure that query modification works, e.g. https://mygene.info/v3/query?q=TRAJ4&entrezonly=true&fields=type_of_gene,+symbol&size=100&species=human&suggest_from=symbol%5E2,alias&type_of_gene=protein-coding still returns an `other` type of gene. Unless I am mistaken?
