### ISSUE TITLE
Google analytics has not been added

### ISSUE THREAD

**Issue by marz0** [cognoma/frontend#107]
Once [google analytics](https://analytics.google.com/) has been setup by one of the maintainers/owners, the proper code [can be added](http://jasonwatmore.com/post/2015/11/07/angularjs-google-analytics-with-the-ui-router) in order to get more insight about the users of cognoma.

**Comment by rdvelazquez** [comment]
This would be a nice addition to be able to understand how Cognoma is being used. I'd be curious to hear from @dhimmel on if there are downsides to having analytics set-up... will some researchers be wary of using a service if their particular gene pathways or gene/disease combinations of interest could be visible to others before they are ready to publish?

It looks like the free version of google analytics would likely have everything that we would need. @marz0 do you have experience setting this up? Is there an option to have google analytics accessible by multiple users or does it have to be tied to a single gmail account?

**Comment by ramenhog** [comment]
@dhimmel could you get me the GA code needed to plop this in here?

**Comment by dhimmel** [comment]
Needs @cgreene to create a "new property" on Google Analytics for "Cognoma"

**Comment by cgreene** [comment]
@ramenhog : UA-20583020-12
