### ISSUE TITLE
Create a separate UX repo. in the project

### ISSUE THREAD

**Issue by bdolly** [cognoma/frontend#11]
At the meetup on Sept. 6 the front-end group decided that it would be beneficial to have a separate User Experience repo. inside the project so that User Experience specific issues can be tracked and evolve separately from the technology stack and development on the frontend

**Comment by cgreene** [comment]
@bdolly : Would a 'label' for UX in this repo serve the same purpose? This would allow quick filtering to only these issues. I'm happy to add another repo, but I want to make sure that we keep issues maximally discoverable for the entire cognoma community.

**Comment by bdolly** [comment]
@cgreene I can see how a 'label' would be valuable in this case. Our thinking was that a separate repo would help UX deliverables (wireframes, storyboards, use cases, etc.) stay separate from the front-end tech stack deliverables (html, css, js). Either way I think would be effective so it's your call on how you want to organize it, main goal is to start a UX track for the project.

**Comment by cgreene** [comment]
Made a UI/UX label for the moment. If it does turn out to become more burdensome this way, we'll make a repo instead! Thanks!

**Comment by dhimmel** [comment]
I created [`cognoma/uiux`](https://github.com/cognoma/uiux) and made @bdolly a maintainer.

Let me know if `uiux` is the best name or we should change it.
