### ISSUE TITLE
Discussion between the Data and Front-end teams. 9/6/2016 Meetup Notes.

### ISSUE THREAD

**Issue by keenleo** [cognoma/frontend#12]
### Summary

The data and front-end teams meet and discussed how the a researcher might interact with the application. 

We asked our selves the question. As a scientist/researcher how do I select the genes and parameters to be submitted to machine learning?

The data team shared an [example ML that started with a pathway](https://github.com/cognoma/machine-learning/blob/master/3.TCGA-MLexample_Pathway.ipynb). A heat map showing the percentage of mutation across different cancer types, In [16], was used to show tissues that did not demonstrate aberrations. This was used to discuss a possible first case. In this use case ntroducing these summary statistics and visualizations during the selection and input process could improve UX in the gognoma application. 

We then discussed what dimensions might be used during the input process and other ways data visualizations might be used during the input process.
### First Use Case

Question to answer 
- How can we expose summary statistics during the gene selection process?

Step one make selections on the possible dimensions below
- Tissue type (aka cancer type)
  - 33 different options
- Age
  - Range box free form
- Gender
  - All/Male/Female
- Genes
  - Pathway, single gene, ad-hoc group of genes
    - enable add or remove
    - auto complete
    - on add or remove

Step two
- "pre classification" before the gene's and tissues are submitted to machine learning.
- expose summary statistics to the user so that the input parameters can be adjusted
### Action Items/Next steps
- Storyboards for use cases
- Compile list of pathways
- Compile list of sites or services that provide the functionality required in gognoma app selection process. 
  - can they be leveraged?
  - can the user experience be improved?
### Questions
- Should UX/UI be separate from Front-end? - Ben will submit an issue
- What software should we use to story boarding and wire-framing.
  - Adobe xD
  - invisionapp.com
  - pen and paper
  - git issues
  - other
- Should we store parameters chosen by the researcher
  - How much do we store?
### Other Notes and Learning

We also learned that Data sets in their initial state have gene symbol.  Users will likely know the gene symbols; they may not know the gene ID's. There is a one to many relationship between the gene symbols and the IDs. The machine learning group has a method to map gene symbols to IDs

**Comment by gwaygenomics** [comment]
excellent recap @keenleo - it sounds like the frontend now has some ammunition to begin making the next steps! Implementing the first use case as a working model is the priority.

To begin discussion of some of your Questions above.

> Should UX/UI be separate from Front-end? - Ben will submit an issue

@bdolly submitted issue #11 - we can discuss this there. @dhimmel do you have any thoughts about this?

> Should we store parameters chosen by the researcher

For this point, do you mean that we store all parameter choices, or just the final choice parameters? We will definitely need to store at the very least the final parameters to send them as json to the backend.

One thing we may want to consider as a potential use case: I can totally see a cancer biologist experimenting here with different gene sets and different tissues - it would be really cool if there is an option to "shelve" queries that build a `query list` - something that can be viewed on a different screen. This is the screen that would be directly before a user sends off the jobs. This way the user can submit multiple jobs testing a similar hypothesis and can directly compare results

**Comment by keenleo** [comment]
@gwaygenomics 

> For this point, do you mean that we store all parameter choices, or just the final choice parameters? We will definitely need to store at the very least the final parameters to send them as json to the backend.

Should we store all of the decision made by the researcher? For instance, a researcher started with a pathway, looked at the mutation heatmap then removed half of the genes. Then looked at a different dimension and removed a further sub set of genes. Do we persist the decisions they made and the dimensions they viewed or just the final set of genes?

**Comment by gwaygenomics** [comment]
> Should we store all of the decision made by the researcher?

I don't think we need to store all of the decisions. I think it is sufficient to store only the final list of genes/tissues. 

Although I could eventually see some functionality that allows a researcher to test many hypotheses simultaneously with some sort of queue system. Then we can add a button that "stores" a snapshot of the current data selection that will direct the queue to a separate screen before sending out a final parameter list to the backend
