### ISSUE TITLE
Create a landing page for cognoma.org

### ISSUE THREAD

**Issue by dhimmel** [cognoma/frontend#126]
When a user goes to cognoma.org, it would be nice to have a landing page with a simple overview of what cognoma is. Currently, cognoma.org immediately displays the analysis builder, which probably confuses new users who don't have any context.

@ramenhog and I were discussion and I've come up with some text snippets that could be appropriate for the landing page.

***

Welcome to Cognoma
_putting machine learning in the hands of cancer biologists_

Use Cognoma to predict cancer mutations from gene expression profiles, based on public TCGA data.
Start by selecting which mutations and cancer types to model. Based on your selection, Cognoma will run the analysis and email you a Jupyter notebook with the results.

Cognoma is an open source tool created by the Philadelphia community, including the [DataPhilly Meetup](https://www.meetup.com/DataPhilly/), the [Childhood Cancer Data Lab](http://www.ccdatalab.org/) at Alex's Lemonade Stand Foundation, and the [Greene Lab](http://www.greenelab.com/) at Penn. Learn more or ask questions on the project's [GitHub](https://github.com/cognoma/cognoma).

**Comment by ramenhog** [comment]
<img width="1678" alt="screen shot 2018-02-06 at 1 53 53 pm" src="https://user-images.githubusercontent.com/4724065/35879313-dc03bb9a-0b48-11e8-9548-c47f7e916848.png">

**Comment by dhimmel** [comment]
That looks great. In the next couple weeks, I can work on creating the visualization for the right side. I think a sketch of the machine learning model would be good. Perhaps something based on http://slides.com/dhimmel/launch#/1/4

What do you think about adding a paragraph break before "Use Cognoma to"? Perhaps get rid of the paragraph break after this sentence.

**Comment by ramenhog** [comment]
Sure, you mean instead of the illustration?

Yeah, I can do that. That makes more sense 👍

**Comment by dhimmel** [comment]
> Sure, you mean instead of the illustration?

Ah did you make this illustration on the right? I thought perhaps it was a stock image.

I'm fine with keeping it, perhaps updating the parts to be a little less generic.

**Comment by ramenhog** [comment]
Nah, it's a stock image with "cognoma green", but Deepa thought it could fit in nicely on the landing page and also liked the collaborative nature of the image. We can definitely update it in the future though.
