### ISSUE TITLE
Create "enter your email for results" modal

### ISSUE THREAD

**Issue by ramenhog** [cognoma/frontend#133]
When user submits a proper query, an alert box pops up prompting them to enter an email currently, without much context.

A better (less sketchy?) workflow would be having a modal pop up that explains that the query is processing and they can wait for the Jupyter notebook link on this page without refreshing or they can enter an email to be notified once its completed. What do you think @dhimmel ?

**Comment by dhimmel** [comment]
Agree! That would be much more user friendly

**Comment by dvenprasad** [comment]
Potential Copy:
Your analysis is being processed. 
Processing usually takes X to Y minutes/hours.
Enter your email and we will email you a Jupyter Notebook with the results

@dhimmel Do we have a rough estimate as to how long an analysis can take? It would be helpful to add that information. People will be more likely to be less annoyed at inputting their email.

**Comment by dhimmel** [comment]
Anywhere from 3 minutes to hours (if server load is high, unlikely). Usually around 5-15 minutes.
