### ISSUE TITLE
Email marketing automation

### ISSUE THREAD

**Issue by ramenhog** [cognoma/frontend#136]
Alex's seems to be using Mailchimp for email automation and it'd be good to utilize that with Cognoma to be able to send out "your analysis is completed" email and such.

**Comment by ramenhog** [comment]
@Miserlou had suggested it would be a good idea to build an email list via the emails collected on Cognoma. Is this something we'd be interested in doing @dhimmel @cgreene ?

**Comment by cgreene** [comment]
Yea - if Alex's is maintaining Cognoma and there's a "don't contact me about other CCDL/alex's items" checkbox they can unselect, this seems totally reasonable to me.

**Comment by ramenhog** [comment]
Do we know who has or how to get access to the Alex's Mailchimp account?

**Comment by cgreene** [comment]
Hmm - @lemonadejay would know. Let me ping him.

**Comment by lemonadejay** [comment]
Where would this go on Cognoma?  I think ernie could probably set up a button people to subscribe for Cognoma specific emails.

**Comment by ramenhog** [comment]
When the user submits their query on Cognoma, an alert box pops up prompting them to enter their email so they can get the Jupyter notebook links via email when the analysis is done. Do we want to also collect their emails at that stage in the process?

**Comment by ramenhog** [comment]
@lemonadejay Here's a GIF of the process:

![submit-query](https://user-images.githubusercontent.com/4724065/36227869-6c963e6e-11a0-11e8-8782-e15a6c2f1260.gif)
