### ISSUE TITLE
Cannot submit query: user is null or undefined

### ISSUE THREAD

**Issue by dhimmel** [cognoma/frontend#158]
Just got a "User is null or undefined" message when I tried to submit a query. Screenshot below:

![cognoma-null](https://user-images.githubusercontent.com/1117703/36678418-b4841f1a-1ade-11e8-9a16-9011ed1f3552.png)

Possibly related to https://github.com/cognoma/frontend/issues/133 or https://github.com/cognoma/frontend/issues/63. Also possibly a backend issue?

**Comment by kurtwheeler** [comment]
This was a backend issue related to migrating AWS accounts. It's now resolved.
