### ISSUE TITLE
Blurry Query Submit Modal (Safari)

### ISSUE THREAD

**Issue by dcgoss** [cognoma/frontend#163]
First of all, @ramenhog I want to congratulate you on a beautiful redesign of the Cognoma UI/UX — it really looks great and made me smile. When I left the Greene Lab last summer, cognoma/frontend was our weak spot — it's awesome to see the upgrades it needed finally being implemented.

Now for a small bug. When I went to submit a modal on Safari, the modal had this weird blurry look to it. I'm on my school laptop so can't access devtools at the moment to investigate, but thought I'd throw up a screenshot for the record.

Safari:
![screen shot 2018-03-27 at 10 15 37 am](https://user-images.githubusercontent.com/7605010/37973569-cf875ca6-31a8-11e8-8cfa-035ccfb29bda.png)

Comparison to Chrome:
![screen shot 2018-03-27 at 10 22 19 am](https://user-images.githubusercontent.com/7605010/37973562-cb6b17e8-31a8-11e8-8c88-bf4b83b70c3f.png)

**Comment by ramenhog** [comment]
Thanks @dcgoss !

Yeah, I think I know what this issue might be. There's something with CSS transforms (which is what is being used to vertically/horizontally align the modal) and blurry text for some reason: https://stackoverflow.com/questions/31109299/css-transform-translate-50-50-makes-texts-blurry
