### ISSUE TITLE
post-classification visualizations

### ISSUE THREAD

**Issue by BobMiller** [cognoma/frontend#18]
Opening this as an offshoot of the #13, at the suggestion of Dan ( @dhimmel ). 

Basically we need to come up with a minimal list of visualizations for our initial release. Later we can add more bells and whistles. Hopefully Dan ( @dhimmel ), Greg ( @gwaygenomics ) and Casey ( @cgreene ) as well as anyone else can weigh in.  

Initially our release is going to have one algorithm - Logistical Regression. So we need to determine what kinds of outputs (graphs, charts, tables, etc.) will best help cancer researchers.

I am thinking a

1) a heat map to show which gene tissues combo's have the most effect (this could also be useful in the pre-classifier phase)

2) a Table showing the top predictors

3) ROC Charts

4) Box and whisker chart

What do you guys think?

**Comment by awm33** [comment]
Something that would be cool, is if the JSON output could create a dashboard using a configuration. Then we wouldn't have to program separate dashboards per algorithm or have algorithm specific code in the frontend. Machine learning implementers running a local copy could play with the output. Config could also be separately stored the db or statically stored.

That might be ambitious for the initial release, but something to think about. Even if the configs are hardcoded for now, building angular directives around some sort of configuration gets us closer to that.

Something else to think about is allowing users to move around and hide the different charts/tables/stats. So when they link or share with colleagues they can highlight different things.

**Comment by dhimmel** [comment]
@BobMiller, here are the visualizations that come to my mind. I'll reference cell numbers from [this notebook](http://nbviewer.jupyter.org/github/cognoma/machine-learning/blob/5199430cf82bcb3763084e559e4f6d563df656a5/2.TCGA-MLexample.ipynb):

1. ROC Curve showing performance (Cell 17)
2. Distribution of positives versus negatives (Cell 25)
3. Cross-validation performance grid (Cell 15)
4. Table of feature coefficients (Cell 21)
5. Table of predictions for each sample (Cell 23)
