### ISSUE TITLE
Creation of base application dashboard html5 markup 

### ISSUE THREAD

**Issue by bdolly** [cognoma/frontend#19]
@BobMiller can you please create the base HTML5 markup for the application dashboard in the `develop`branch inside of app/js/components/app/app.tpl.html using the [Twitter Bootstrap ](http://getbootstrap.com/) framework. 

The jpgs for the MVP can be found in cognoma/uiux repo at https://github.com/cognoma/uiux/blob/master/wireframes/exports/invision_app_prototype/
Those should allow you to use the bootstrap grid to create the sidebar and the column. If you need individual graphic assets exported from the design please let me know and I can provide them. The color scheme in the design is mostly arbitrary at this point.

**Comment by BobMiller** [comment]
I'll be working on it today. Initially I'll create a blank layout with no graphics then fill the graphics in. If you have the graphics files you can email them to me. I will not need them right away, but if I get them in the next few days that would be good.

**Comment by dhimmel** [comment]
> I'll be working on it today.

Awesome! Nothing like some Sunday coding.

> If you have the graphics files you can email them to me.

You can also drag and drop images into GitHub issues.

**Comment by bdolly** [comment]
DEPRICATED old mark up
