### ISSUE TITLE
Component Creation: Mutations Overview

### ISSUE THREAD

**Issue by bdolly** [cognoma/frontend#20]
@txnnxr welcome aboard! When you have a chance to familiarize yourself with the front-end scaffolding in the `develop` branch could you please start on the basic markup for the Mutations Overview component in the Query sidebar. This can be created in the `develop` branch of frontend repo app/js/components/MutationsOverview/mutations_overview.tpl.html 

Once you have created the basic markup for the component we will work on integrating it into Angular and hooking it up with the different data/states it needs to communicate with the rest of the application logic.

You can view the exported jpgs of the MVP at https://github.com/cognoma/uiux/tree/master/wireframes/exports/invision_app_prototype going through these should give you an idea of the layout for component. You can also view the [MVP prototype](https://invis.io/5P8PM61R8) and click through to give you an idea of the functionality.

**Comment by dhimmel** [comment]
Welcome @txnnxr! Don't be shy if you have any questions.

**Comment by txnnxr** [comment]
@bdolly sorry for some reason I wasn't receiving notifications on this. Will get started immediately just to be clear I'm starting on the Mutations in the query bar:
![screen shot 2016-10-11 at 12 07 59 pm](https://cloud.githubusercontent.com/assets/3223394/19278531/88e30386-8fab-11e6-9073-33010ab7f76e.png)
Does that also include the adjacent expanded view?:
![screen shot 2016-10-11 at 12 08 05 pm](https://cloud.githubusercontent.com/assets/3223394/19278540/91650540-8fab-11e6-8e03-bd53a3b30ec9.png)

**Comment by bdolly** [comment]
@txnnxr just the overview component, I will be working on the expanded view component this week and the drag and drop functionality
