### ISSUE TITLE
Component Creation: Query Set - Disease Type

### ISSUE THREAD

**Issue by bdolly** [cognoma/frontend#25]
Create in `develop` branch basic HTML5 markup and styling for the Gene/Mutations Set Component with static data in the template. This can be created inside `app/js/components/queryBuilder/querySets/querySetDiseaseType/` , there maybe the need to create additional child components which should be nested inside this directior have their own directories and templates. 

The design for the populated state of this component can be found at https://github.com/cognoma/uiux/blob/master/wireframes/exports/invision_app_prototype/2.3-Cognoma-SampleSelection-DISEASE-ADDED.jpg

**Comment by bdolly** [comment]
@dhimmel  not sure how I can assign this to Tanner (@txnnxr) he's not showing up in the list of possible assignees

**Comment by dhimmel** [comment]
I sent @txnnxr an invite, which if he accepts should make him assignable. In the meantime, we can get by with mentions.
