### ISSUE TITLE
Component Creation: Query Set - Mutations

### ISSUE THREAD

**Issue by bdolly** [cognoma/frontend#26]
Create in `develop` branch basic HTML5 markup and styling for the Gene/Mutations Set Component with static data in the template. This can be created inside `app/js/components/queryBuilder/querySets/querySetMutations/` , there maybe the need to create additional child components which should be nested inside this directior have their own directories and templates.

The design for the populated state of this component can be found at https://github.com/cognoma/uiux/blob/master/wireframes/exports/invision_app_prototype/1.3-Cognoma-GeneSelection-GENE-ADDED.jpg

**Comment by bdolly** [comment]
@txnnxr think you can knock this out?

**Comment by txnnxr** [comment]
@bdolly I'll get on these before tonight's meeting

**Comment by bdolly** [comment]
@txnnxr cool, I'm going to be running a little late tonight but I want to go over the project structure and roadmap with the front-end team tonight so we can get rocking on some dev for this

**Comment by bdolly** [comment]
closed with #34
