### ISSUE TITLE
Component Creation: Query Parameter Selector - Mutations 

### ISSUE THREAD

**Issue by bdolly** [cognoma/frontend#30]
need to create in `develop` branch the basic HTML5 markup for the **Gene Search/queryParamSelectorGenes** component. 

The design for this can be found in https://github.com/cognoma/uiux/blob/master/wireframes/exports/invision_app_prototype/1.1-Cognoma-GeneSelection-SEARCH.jpg

**Comment by bdolly** [comment]
@txnnxr think you could knock this out? I've been grinding out unit tests for the base components we have already so that when we do launch this thing we'll know it's tested and solid. 

There are a couple of **component states** for this component:

- **`clean/pristine`**: no user input in the search bar 
    - This will show the instructions for how search for genes, [design mock here](https://github.com/cognoma/uiux/blob/master/wireframes/exports/invision_app_prototype/2-Cognoma-SampleSelection-EMPTY.jpg)
- **`dirty`**: user has started typing input
   - shows the results of the elastic gene search, [design mock ](https://github.com/cognoma/uiux/blob/master/wireframes/exports/invision_app_prototype/1.1-Cognoma-GeneSelection-SEARCH.jpg)
- **`dirty:hovered`**: activates the querySetMutations state, [design mock ](https://github.com/cognoma/uiux/blob/master/wireframes/exports/invision_app_prototype/1.2-Cognoma-GeneSelection-GENE-HOVER.jpg)
- **`dirty:selected`**: user has selected a result 
   - removes or highlights the user selected result from the results list, [design mock](https://github.com/cognoma/uiux/blob/master/wireframes/exports/invision_app_prototype/1.3-Cognoma-GeneSelection-GENE-ADDED.jpg) 

I believe Angular has [default form states](https://docs.angularjs.org/guide/forms) that will help with this. This component will also need to leverage a Service that interacts with the back-end to get the elastic search results list. I would hitup @awm33 and/or @dhimmel to see if they could provide you with a sample json set of genes to mock this service with. 

As always feel free to let me know if you have any questions with this.

**Comment by txnnxr** [comment]
@bdolly I'm on it. 

@awm33 @dhimmel if either of you could help me out in getting some json to test this component that would be great, or just a list of keys/values would also be helpful and I could just use filler data.

**Comment by dhimmel** [comment]
@txnnxr are you asking for information to populate the gene cards? If so, I think we're leaning towards using a service called mygene for gene selection: https://github.com/cognoma/core-service/issues/29#issuecomment-252637420. Our adoption of mygene will depend on when they're able to roll out a [new feature to allow partial search](https://github.com/SuLab/mygene.info/issues/4#issuecomment-255196323). But let's assume we'll be able to use it for now.

In that case, this query returns a JSON with all the genes with `super` in their name: https://mygene.info/v3/query?q=super&species=human&entrezonly=true. @txnnxr is that what you want?

**Comment by bdolly** [comment]
@txnnxr where are we at with this? I'm going to start working on the Mock backend service soon to pull data for this from the https://mygene.info/v3/ endpoint

**Comment by bdolly** [comment]
wrapped this functionality into the MutationsService
