### ISSUE TITLE
Component Creation: Query Builder Wizard Bar

### ISSUE THREAD

**Issue by bdolly** [cognoma/frontend#33]
Create in `develop` branch basic HTML5 markup and styling for the queryBuilderWizard component in `app/js/components/queryBuilder/queryBuilderWizard`.  The functionality for this can be seen in the clickable prototype at https://invis.io/5P8PM61R8 and the flat design files can be found in [uiux repo](https://github.com/cognoma/uiux/tree/master/wireframes/exports/invision_app_prototype) if graphic assets are needed please let me know and I can export them into the app/images directory

This should ideally function using the [angular ui router](https://ui-router.github.io/) to change and update the application state.

**Comment by ramenhog** [comment]
We think this is completed, but feel free to open if not the case.
