### ISSUE TITLE
Angular Service creation: Query Param Selector/Gene Search

### ISSUE THREAD

**Issue by bdolly** [cognoma/frontend#37]
A mock angular backend service needs to be created that will provide Gene/Mutation search result json to the `queryParamSelectorGenes` component search functionality. 

@awm33 @dhimmel this service will provide the data to front-end for the gene search results. That data has been discussed somewhat in https://github.com/cognoma/frontend/issues/30 with a mention of using https://mygene.info/v3/ queries, is that the endpoint that the service should implement queries with or should we roll-up a custom mock httpBackend that will be swapped out for use with the [core-service /genes api](https://github.com/cognoma/core-service/blob/master/doc/api.md) endpoint eventually?

**Comment by dhimmel** [comment]
> That data has been discussed somewhat in #30 with a mention of using https://mygene.info/v3/ queries, is that the endpoint that the service should implement queries with

I think there's a 90% that we go with mygene.info API calls for searching for genes and populating gene cards.

> should we roll-up a custom mock httpBackend that will be swapped out for use with the [core-service /genes api](https://github.com/cognoma/core-service/blob/master/doc/api.md#gene-genes) endpoint eventually?

I would say let's not do this right now given there's a large chance we won't go this direction. We may still end up querying the core-service/genes api for our results viewer.
