### ISSUE TITLE
JavaScript/Web Designers

### ISSUE THREAD

**Issue by BobMiller** [cognoma/frontend#4]
Just to let you know, the Philly JavaScript meetup is scheduled for next Wed (July 27th) at 6:00PM. The location is 

Quorum at the Science Center
3711 Market Street, Floor 8
Philadelphia, PA 19104

I have put in a formal request to do a lightning talk (about 5 minutes) on Project Cognoma. Hopefully a few members of the group will volunteer to join our front end group. If anyone else wants to join me, let me know.

If for some reason, we can not get on the schedule, I intend to show up, make a general announcement  about our need for help, and beat the bushes for some volunteers.

**Comment by gwaygenomics** [comment]
@BobMiller That sounds great! @cgreene is out of town July 27th but I am willing to help represent cognoma. Karin also sent an email out to them asking for volunteers - so we do have some feelers out already.

Please keep us updated!

**Comment by dhimmel** [comment]
Closing since the Philly JavaScript meetup date has passed.
