### ISSUE TITLE
Defining a custom elastic search query for mygene.info

### ISSUE THREAD

**Issue by dhimmel** [cognoma/frontend#59]
Based on our feedback, @cyrus0824 and @newgene have added a new custom user query feature to mygene.info, as described in https://github.com/SuLab/mygene.info/issues/4#issuecomment-273294532. So I think we will have to submit a pull request adding our custom query to [`SuLab/biothings.userqueries/mygene`](https://github.com/SuLab/biothings.userqueries/tree/master/mygene) -- unless the `prefix` query is already what we need.

Anyone interested in tackling this issue? Tagging @awm33 and @cgreene in case they otherwise wouldn't get notified.

**Comment by ramenhog** [comment]
This has been implemented. There are some remaining issues with the mygene.info queries. See #106 & #109.
