### ISSUE TITLE
Results Viewer View/App 

### ISSUE THREAD

**Issue by bdolly** [cognoma/frontend#64]
A view needs to be created to show the results of a given classifier/query and offer data visualizations. 

@dhimmel can you please provide some functional as well as layout requirements for this view, specifically those that pertain to the data visualization(s) needed?

**Comment by w0lya** [comment]
@dhimmel

**Comment by bdolly** [comment]
@dhimmel how do I make it so I can add @w0lya to the assignees for front-end task?

**Comment by w0lya** [comment]
@dhimmel @bdolly probably you guys need to add me to project members? haven't worked with github boards, just assuming

**Comment by dhimmel** [comment]
Okay once @w0lya accepts her [invitation](https://github.com/cognoma/frontend/invitations), you should be able to assign her.

Give me a day or two to sketch out a preliminary results viewer. In the meantime, the visualizations and data tables will be based on cells 12+ in [`2.TCGA-MLexample.ipynb`](https://github.com/cognoma/machine-learning/blob/553d704d67ebd246b38333dabaf16b32657d0de1/2.TCGA-MLexample.ipynb). We're working on retrofitting these elements for web display. Specific examples include:

+ https://github.com/cognoma/machine-learning/pull/77
+ https://github.com/cognoma/machine-learning/pull/74

**Comment by w0lya** [comment]
@dhimmel accepted, thanks! 
In the meantime I have some stuff to do in terms of setup anyway :)

**Comment by ramenhog** [comment]
Closing since we switched to a notebook viewer for output.
