### ISSUE TITLE
Application Start/Intro Screen

### ISSUE THREAD

**Issue by bdolly** [cognoma/frontend#66]
An Introduction to Cognoma screen needs to be created that would access by the main application route. Layout, documentation and requirements for this screen can be found in the [UI/UX wireframes](https://github.com/cognoma/uiux/tree/develop/wireframes).  

The [layout](https://github.com/cognoma/uiux/blob/develop/wireframes/1-InitialScreen.jpg) should follow the content given in the wireframe but the header and sidebar should be ignored as those need to match the existing build until further design updates are implemented.

**Comment by ramenhog** [comment]
#126 closes this ticket
