### ISSUE TITLE
Switch default branch to develop

### ISSUE THREAD

**Issue by dhimmel** [cognoma/frontend#70]
@bdolly what do you think of switching the default branch on GitHub from `develop` to `master`? I'd like to address two things:

1. `cognoma/frontend` contributions getting counted in our [contribution analysis](https://github.com/cognoma/cognoma/tree/714aaebeb2c262f70cafb759bb9da5770c176745/contrib), which only looks at default branches of repos.
2. when someone comes across this repository, they are likely to miss the extent of activity, since it's all taking place on an out-of-view branch.

Another solution would be syncing `master` with `develop` more often. @bdolly and @awm33 what do you think is best? [`cognoma/core-service`](https://github.com/cognoma/core-service) also has similar issues.

**Comment by bdolly** [comment]
@dhimmel is there a way to make `develop` branch the default branch for the repo. ? I would prefer to keep all work in the `develop` branch as to follow the [gitlfow](http://nvie.com/posts/a-successful-git-branching-model/) methodology. This will allows us to hook in deployment automations  in the future and make for better version and release control over the life of the project. 

I should however merge the `develop` README.md to the `master` and the wiki so that when you first visit the project the structure will be presented more clearly without having to dig around branches and figure it out. 

@awm33 thought?

**Comment by awm33** [comment]
@bdolly @dhimmel At that point, isn't `master` production? I've never used gitflow. I've always had `master` be the bleeding edge aside from task specific development branches. Sometimes I've used a `production` branch to automate deployment.

You can change the default branch in the repo settings.

**Comment by dhimmel** [comment]
@bdolly you can change the branch settings at https://github.com/cognoma/frontend/settings/branches.

I don't have a strong opinion on whether the "bleeding edge" branch should be master or something else, but I do think the "bleeding edge" branch should be the default. @bdolly would it interfere with gitflow to make develop the default branch on GitHub? What do you think is best?

**Comment by bdolly** [comment]
@dhimmel @awm33 Come to think of it we did create a `production` branch for auto deployments, so it's cool to make `develop` the default for the repo. I think in the start we decided to leave `master` as a sandbox branch for new comers and move auto deployments to `production`

**Comment by dhimmel** [comment]
@bdolly cool, I'll let you make the switch. Just gave you admin so you shouldn't run into any problems. Will let you decide what to do with `master`. It may not even be a bad idea to delete it completely if it's going to cause more confusion than its worth.

**Comment by dhimmel** [comment]
Changed the default branch for `frontend` and `uiux` to `develop` from `master`. FYI, this is how the GitHub settings described the default branch:

> The default branch is considered the “base” branch in your repository, against which all pull requests and code commits are automatically made, unless you specify a different branch.
