### ISSUE TITLE
Frontend Production Environment 

### ISSUE THREAD

**Issue by awm33** [cognoma/frontend#71]
cognoma.org

Requirements
- S3 / CloudFront site
- Needs CORS access to api.cognoma.org
- Continuous Deployment - on the `master` (production) - should be able to do this in CircleCI

**Comment by awm33** [comment]
@amann Wanna help :D

**Comment by kurtwheeler** [comment]
@ramenhog I just came across this. It looks like this might be entirely done. Is that correct?

**Comment by ramenhog** [comment]
@kurtwheeler Yup!
