### ISSUE TITLE
Deploy to GitHub pages

### ISSUE THREAD

**Issue by dhimmel** [cognoma/frontend#74]
This issue is for deploying the webapp to http://cognoma.org. From my understanding, the static webapp files are created in the `build` directory by running:

```sh
npm install
npm run build
```

As per https://github.com/cognoma/frontend/pull/73#issuecomment-290589794, we will use [`ghp-import`](https://github.com/davisp/ghp-import) to overwrite the `gh-pages` branch with the contents of the `build` (after building the app locally).

We will need to make sure the `build` directory contains `CNAME` file whose contents are:

```
cognoma.org
```

@bdolly, should we just track `build/CNAME` in git, or do we have to do something special so `npm run build` doesn't overwrite it?

**Comment by dhimmel** [comment]
> do we have to do something special so `npm run build` doesn't overwrite it?

`npm run build` overwrites all contents of `build/`. So we need to have `npm run build` copy the CNAME file into `build`. Here are a [few methods](https://surge.sh/help/copying-extra-files-into-the-directory-you-publish) for copying, but I haven't had success yet.

**Comment by dhimmel** [comment]
@bdolly implemented the CNAME fix in https://github.com/cognoma/frontend/pull/77.

http://cognoma.org/ currently returns 404, but I think that's a GitHub issue. Will check back tomorrow and if still not resolved contact GitHub.

**Comment by dhimmel** [comment]
I contacted GitHub Support about the Pages 404. Antonio responded:

> Thanks for reaching out! Hmm, it looks like there was a small glitch with setting your custom domain. I triggered a new build, and your site should now be displayed on your custom domain.

> However, your site is currently loading a blank page, probably because `js/main.js` is 404ing. It doesn't look like you have that folder in your gh-pages branch. Could you upload that file to your gh-pages branch, and then see if that works?

So the issue with GitHub is fixed. Now it looks like we've got an issue that there is no `js` directory in our `gh-pages` branch. @bdolly any ideas why not?

**Comment by bdolly** [comment]
@dhimmel my guess would be that maybe your `ghp-import` command didn't do a recursive copy to `gh-pages` branch

**Comment by dhimmel** [comment]
That's odd as `ghp-import` [recursed and copied](https://github.com/cognoma/frontend/tree/ea7ff5b42fa7946c2e4330d1c0edf2eeb060e562) the `css` and `images` dir. I'll look into the matter.

@bdolly can you confirm that the `build/js` directory exists in your local repo?

**Comment by bdolly** [comment]
Looks like it's missing in my local. I'll check into it tomorrow and see if I can adjust the the gulp task to include it.

**Comment by bdolly** [comment]
@dhimmel I updated the `$npm run build` task on my local `develop` branch to include the /js directory into the build. Do you want me to make a PR to merge that into cognoma:develop branch?

**Comment by dhimmel** [comment]
> Do you want me to make a PR to merge that into `cognoma:develop` branch?

Yes!
