### ISSUE TITLE
More Design

### ISSUE THREAD

**Issue by BobMiller** [cognoma/frontend#8]
Here are a few more potential screen layouts. The are in HTML, just unzip the files, everything you need to run them is included(hopefully?). Theyn use bootstrap, so you need to view then when you have a web connection.

I was going for function over style, so it pretty rough.

It nowhere near complete, so START BY OPENING THE WELCOME SCREEN, click on anonymous login, and on the main screen, click on the results menu, and the choose  menu click 
Results for Current Classifier. Check out the tabs on this screen.

[CognomaMain.zip](https://github.com/cognoma/frontend/files/409972/CognomaMain.zip)

**Comment by keenleo** [comment]
@BobMiller, this looks really good. I went ahead and started work an [angular version](https://github.com/keenleo/frontend/tree/master/app) of this. 

The routes and angular/bootstrap dependencies working. There is a rough templating structure, based on angular seed. 

The only link in nav that routes to a working page is results>results for current classifier. I am working on adding the content by parsing a json object. Hopefuly this will help us give constructive input into the rest api.

Please let me know if you have any questions. I'll try my best to make the meetup tomorrow.

**Comment by BobMiller** [comment]
Thanks Chris for looking at this. I have made some minor changes to the results screen. Mostly minor formatting changes so they look OK in other browsers and screen sizes. Here is the zip of the latest version of the html. 

[CognomaMain2.zip](https://github.com/cognoma/frontend/files/432825/CognomaMain2.zip)

Looking forward to speaking with you if you make it tonight.
-Bob Miller

**Comment by dhimmel** [comment]
Awesome work @BobMiller and @keenleo. It's nice to see a preliminary frontend (and a slick one as well).

@BobMiller in the future, it's critical that we track code using git. I'm going to try to rewrite history, so you get credit for your contributions in the git history. Will keep everyone posted on this thread.

For now, @keenleo and @BobMiller: what name and email do you want to use for your git commits? @keenleo you have something weird going on where [your commits](https://github.com/keenleo/frontend/commits/master) show up as from "Chris Fuller" or @keenleo. Maybe [this page will help](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/).

**Comment by keenleo** [comment]
@dhimmel Thanks, I'll take a look at my account. I'd like my commits to show up as from "Chris Fuller"

@BobMiller I tried to make the meet up but it wasn't in the cards.. Ill definitely make the next one. I am going to take a look at your changes and incorporate them into the angular version. I'm also going to work on routes and templates for other parts of app.

**Comment by dhimmel** [comment]
@keenleo, can you work off of the repository state in #9. Our priority should be getting that merged / making modifications on top of it.

**Comment by keenleo** [comment]
@dhimmel Wow good timing on your reply! I was just trying to figure out with branch/repository would be best to work off of. Ill work off #9, get the files merged and then make modifications. Thanks again.

**Comment by awm33** [comment]
@keenleo Hey Chris, I've worked with angular in production, if you need help setting it up or reviewing code.

**Comment by dhimmel** [comment]
Okay now that pull request #9 has been merged, the work from this Issue is now in the master branch of this repository. Thanks @keenleo and @BobMiller for getting the frontend off the ground. In the future, the best way to contribute and discuss code is through pull requests.
