### ISSUE TITLE
Missing fonts directory

### ISSUE THREAD

**Issue by dhimmel** [cognoma/frontend#80]
We've deplyed the [`gh-pages`](https://github.com/cognoma/frontend/tree/gh-pages) branch of this repo to http://cognoma.org/ via GitHub Pages: #74.

However, it looks like we're missing the `fonts` directory:

![fonts-cognoma](https://cloud.githubusercontent.com/assets/1117703/24819556/0a1be9d4-1bb3-11e7-864e-ddccb613554f.png)

**Comment by bdolly** [comment]
@dhimmel this is an issue on the `develop` branch as well and has not yet been addressed. I think it might have something to do with the way the bootstrap stylesheet is loaded into the build

**Comment by arielsvn** [comment]
yes, it's because bootstrap's styles reference fonts that are in the node package, but these fonts are not being included when the project is built. It's a configuration issue, I'll add a PR to fix it
