### ISSUE TITLE
Typo: "alogrithm"

### ISSUE THREAD

**Issue by dcgoss** [cognoma/frontend#83]
Should be spelled "algorithm".
Noted in these files:
https://github.com/cognoma/frontend/blob/develop/app/js/components/queryBuilder/queryParamSelector/diseaseTypeInstructions/diseaseType_instructions.tpl.html

https://github.com/cognoma/frontend/blob/develop/app/js/components/queryBuilder/queryParamSelector/mutationsInstructions/mutations_instructions.tpl.html

https://github.com/cognoma/frontend/blob/develop/app/js/components/queryBuilder/queryParamSelector/mutations_instructions.tpl.html

Am on my school computer now, can fix when I get home.

**Comment by dhimmel** [comment]
Cool, will let you make the PR.
