### ISSUE TITLE
Add a "select all diseases" option to the frontend

### ISSUE THREAD

**Issue by dhimmel** [cognoma/frontend#99]
Many users will want to run their analysis on all diseases, or alternatively work backwards excluding certain diseases.

The option / button would select every disease and add them to "SELECTED DISEASE TYPES" pane.

**Comment by rdvelazquez** [comment]
Agreed that this would be a nice addition. I'd like to take a crack at this. 
@dhimmel, @bdolly or @dcgoss let me know if this has been started already or if there's anything I should know before working on this.

**Comment by dhimmel** [comment]
> I'd like to take a crack at this.

Cool!

**Comment by dhimmel** [comment]
On the disease selection page (http://cognoma.org/query-builder/disease-type), when the search bar is blank, all 33 cancers should be displayed. Typing in the search bar should filter these cancers. Currently, the default is to show no cancer.

@rdvelazquez, we have a new frontend specialist in the Greene Lab. Welcome @ramenhog! She can take over addressing this issue, potentially building off of https://github.com/cognoma/frontend/pull/108

**Comment by rdvelazquez** [comment]
Sounds good. Glad Cognoma is getting some help. Welcome @ramenhog!

> when the search bar is blank, all 33 cancers should be displayed.

Agreed. I think a the option to select all diseases (without having to individually click all 33) should also be implemented.

#108 was just a WIP PR to get the ball rolling on this. I'm not sure there will be much of value there but you are certainly welcome to use what you can.

@ramenhog - If you haven't already, I would suggest you connect with @bdolly (not about this issue but just in general) as he was the main architect of the Cognoma frontend.

Good luck, and let me know if there's anything you want help with.

**Comment by ramenhog** [comment]
@rdvelazquez awesome, thanks for the tip!

**Comment by ramenhog** [comment]
Just had a conversation with Deepa about the UX of the button and such, so I'm putting a checklist of things to do for it here so I don't forget:

- [ ] Move instructions for disease type selection over to Disease Type Set
- [ ] Remove dotted border rectangle from Disease Type Set (since it doesn't really act like a button)
- [ ] Put "Select All" button in the Parameter Selection section
- [ ] Add loading state to the body of the Parameter Selection section
